version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: logs/llm_rag_app.log
        mode: a

loggers:
    mainlogger:
        level: DEBUG
        handlers: [console, file]
        propagate: no

root:
    level: DEBUG
    handlers: [console, file]